### ISSUE TITLE
Menu items - configurable layout?

### ISSUE THREAD

**Issue by brandonneil** [ITS-UofIowa/catering.uiowa.edu#11]
Design-wise, will we be supporting a two-column layout for menu items? Like in their example from http://catering.umich.edu/p/home.html ?

If so, we may want to make these configurable on the list of menu items content block.

**Comment by brandonneil** [comment]
Would like feedback from @adamdelaney on this one.

**Comment by adamdelaney** [comment]
I good with supporting 2 columns.

**Comment by brandonneil** [comment]
So make this configurable? I think they will probably want the option for 2col for menus with a lot of items in a section and have the default be 1col. Thoughts?

**Comment by adamdelaney** [comment]
Yeah, I agree. A configurable option would be a great feature.
