### ISSUE TITLE
Photo paragraph image style

### ISSUE THREAD

**Issue by brandonneil** [ITS-UofIowa/catering.uiowa.edu#12]
What image size do we want to use for the photo paragraph?

If we're going to use a large image, this field might be a good use-case for using the picture module/framework.

With this issue, we will also add manual crop.

**Comment by brandonneil** [comment]
If we want a full-width image in the content, the image would be 1140px wide.

Design review from @adamdelaney requested.

**Comment by adamdelaney** [comment]
Is it possible to have images that fit edge to edge using paragraphs?

**Comment by brandonneil** [comment]
Oh, I was referring to edge-to-edge in the current content region.

No, not really without removing the container in page.tpl.php and setting containers within node templates instead.

**Comment by adamdelaney** [comment]
Have you used this project, https://www.drupal.org/project/edgy?

**Comment by brandonneil** [comment]
No, I haven't - I was kind of hoping we could uninstall panelizer :)

**Comment by brandonneil** [comment]
But if you want to give it a try locally and think it would be worth it that's cool
