### ISSUE TITLE
order manager, webmaster need access to see orders at admin/commerce/orders

### ISSUE THREAD

**Issue by brandonneil** [ITS-UofIowa/catering.uiowa.edu#26]

**Comment by adamdelaney** [comment]
I don't know what's going on here. These roles have to ability to navigate to `admin/commerce/orders` however the view is empty, even though there are orders in the store. I have checked the permission on the view (see attached) it appears as if the correct permsissions
have been assigned. ![wysiwyg](https://cloud.githubusercontent.com/assets/1016880/24871349/f34b8420-1dde-11e7-8636-f3f47e77c988.JPG)

**Comment by adamdelaney** [comment]
These roles can view the order if they navigate to them, but the view is not displaying them at the admin/commerce/orders path.

**Comment by richardbporter** [comment]
Adding `View any Billing information customer profile` the permission to both roles fixed the issue for me. Is that permission going to be a problem?
