### ISSUE TITLE
Initial homepage

### ISSUE THREAD

**Issue by brandonneil** [ITS-UofIowa/catering.uiowa.edu#3]
- [ ] Panel page
- [ ] Repurpose homepage promos from dining.uiowa.edu https://github.com/ITS-UofIowa/dining.uiowa.edu/tree/master/modules/features/dining_promo_entity https://github.com/ITS-UofIowa/dining.uiowa.edu/tree/master/modules/features/dining_promo_views

**Comment by adamdelaney** [comment]
After talking to @brandonneil about the homepage we decided to make it a landing page and place the event_planning block on it.
