### ISSUE TITLE
IE styles testing

### ISSUE THREAD

**Issue by brandonneil** [ITS-UofIowa/catering.uiowa.edu#36]

**Comment by adamdelaney** [comment]
### I resolved the following issues for IE Edge:
- Resolved issue with flex shorthand property and using calc. See: https://github.com/philipwalton/flexbugs#8-flex-basis-doesnt-support-calc
- Resolved issue with calc rounding errors. See: http://stackoverflow.com/questions/16658482/css-calc-function-bug-in-ie
- Resolved issue with IE not supporting object fit. I pushed up a custom modernizr build that detects for object-fit and added conditional css for when object-fit was detected.
