### ISSUE TITLE
“I am planning a…” search

### ISSUE THREAD

**Issue by brandonneil** [ITS-UofIowa/catering.uiowa.edu#4]
>We will build this as a Drupal vocabulary, which content editors can manage within the site. For each term (Wedding, student event, etc) the ability to select which area of the site a user should navigate to will be provided.

- [x] Event Types vocabulary
- [x] Terms have a field to determine where the term sends someone.
- [x] Custom block or pane to be used on the homepage, uses either [Search Autocomplete module](https://www.drupal.org/project/search_autocomplete) or a custom solution by exposing the terms as a json feed and using something like https://twitter.github.io/typeahead.js/

**Comment by adamdelaney** [comment]
I have pushed the catering_planning_block feature to dev.
