### ISSUE TITLE
Venues

### ISSUE THREAD

**Issue by brandonneil** [ITS-UofIowa/catering.uiowa.edu#8]
>We would build out this content type generally as discussed in the meeting. It would have fields available in main locations page filter that would allow for filtering by building, indoor/outdoor, etc as identified by Catering. Each location is really more of a room inside of a building for most large venues.

- [x] Location content type
- [x] Location panel page

**Comment by richardbporter** [comment]
- [ ] Building taxonomy and fields
- [ ] Building field on venues
- [ ] Contact fields on venues
- [ ] 'Get Started' form
